"""updated products table

Revision ID: 41dc5e03112d
Revises: 736bc7e603b2
Create Date: 2020-12-24 22:23:30.469029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41dc5e03112d'
down_revision = '736bc7e603b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('external_id', sa.String(length=60), nullable=False))
    op.add_column('products', sa.Column('quantity', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'products', ['external_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='unique')
    op.drop_column('products', 'quantity')
    op.drop_column('products', 'external_id')
    # ### end Alembic commands ###
